# Generated by Django 5.1.7 on 2025-04-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnos',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='data.patientsinfo'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healt_patient', to='data.patientsinfo'),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='data.patientsinfo'),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='profile_picture',
            field=models.FileField(upload_to='profile_img'),
        ),
    ]
